"""Initial schema - existing tables

Revision ID: 2b867da770a2
Revises: 
Create Date: 2026-01-11 07:17:17.841867

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '2b867da770a2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('readings')
    op.alter_column('consumers', 'name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=255),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('consumers', 'created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_column('consumers', 'address')
    op.alter_column('images', 'image_url',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=512),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('images', 'created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('ocr_results', 'task_id',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('ocr_results', 'value',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('ocr_results', 'confidence',
               existing_type=mysql.DECIMAL(precision=5, scale=2),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('ocr_results', 'status',
               existing_type=mysql.ENUM('pending', 'success', 'error', collation='utf8mb4_unicode_ci'),
               type_=sa.String(length=20),
               existing_nullable=True,
               existing_server_default=sa.text("'pending'"))
    op.alter_column('ocr_results', 'created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index(op.f('idx_image_id'), table_name='ocr_results')
    op.drop_index(op.f('idx_status'), table_name='ocr_results')
    op.drop_index(op.f('idx_task_id'), table_name='ocr_results')
    op.drop_constraint(op.f('ocr_results_ibfk_1'), 'ocr_results', type_='foreignkey')
    op.create_foreign_key(None, 'ocr_results', 'images', ['image_id'], ['id'])
    op.drop_column('ocr_results', 'updated_at')
    op.alter_column('water_meters', 'location',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=255),
               type_=sa.String(length=200),
               existing_nullable=True)
    op.alter_column('water_meters', 'created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_column('water_meters', 'installation_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('water_meters', sa.Column('installation_date', sa.DATE(), nullable=True))
    op.alter_column('water_meters', 'created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('water_meters', 'location',
               existing_type=sa.String(length=200),
               type_=mysql.VARCHAR(collation='utf8mb4_general_ci', length=255),
               existing_nullable=True)
    op.add_column('ocr_results', sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True))
    op.drop_constraint(None, 'ocr_results', type_='foreignkey')
    op.create_foreign_key(op.f('ocr_results_ibfk_1'), 'ocr_results', 'images', ['image_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('idx_task_id'), 'ocr_results', ['task_id'], unique=False)
    op.create_index(op.f('idx_status'), 'ocr_results', ['status'], unique=False)
    op.create_index(op.f('idx_image_id'), 'ocr_results', ['image_id'], unique=False)
    op.alter_column('ocr_results', 'created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('ocr_results', 'status',
               existing_type=sa.String(length=20),
               type_=mysql.ENUM('pending', 'success', 'error', collation='utf8mb4_unicode_ci'),
               existing_nullable=True,
               existing_server_default=sa.text("'pending'"))
    op.alter_column('ocr_results', 'confidence',
               existing_type=sa.Float(),
               type_=mysql.DECIMAL(precision=5, scale=2),
               existing_nullable=True)
    op.alter_column('ocr_results', 'value',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               existing_nullable=True)
    op.alter_column('ocr_results', 'task_id',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               existing_nullable=False)
    op.alter_column('images', 'created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('images', 'image_url',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(collation='utf8mb4_general_ci', length=512),
               existing_nullable=False)
    op.add_column('consumers', sa.Column('address', mysql.VARCHAR(collation='utf8mb4_general_ci', length=255), nullable=True))
    op.alter_column('consumers', 'created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('consumers', 'name',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(collation='utf8mb4_general_ci', length=255),
               existing_nullable=False)
    op.create_table('readings',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('water_meter_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('reading_value', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('image_path', mysql.VARCHAR(collation='utf8mb4_general_ci', length=512), nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['water_meter_id'], ['water_meters.id'], name=op.f('readings_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
